# Numeric Python

In [1]:
import numpy as np

In [2]:
a = [2, 4, 6]
b = [7, 4, 1]

In [8]:
print(a)

[2, 4, 6]


In [3]:
c = a + b
c

[2, 4, 6, 7, 4, 1]

In [5]:
type(b)

list

In [11]:
# np.array(list)
a_array = np.array(a)
print(a_array)

[2 4 6]


In [12]:
b_array = np.array(b)
print(b_array)

[7 4 1]


In [18]:
a_array.shape

(3,)

In [21]:
multi_d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
multi_d.shape

(3, 3)

In [17]:
addition = a_array // b_array
addition

array([0, 1, 6])

## Zeros and Ones

In [25]:
# zeros / ones (shape, dtype=float(default)/int)
zero_1d = np.zeros(6, dtype=int)
zero_1d

array([0, 0, 0, 0, 0, 0])

In [27]:
one_1d = np.ones(6, dtype=int)
one_1d

array([1, 1, 1, 1, 1, 1])

In [30]:
zero_2d = np.zeros((5, 6), dtype=int)
zero_2d

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [35]:
one_2d = np.ones((5, 6), dtype=int)
one_2d

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## Arange

In [41]:
# arange(start, stop, step)
data = []
for i in range(1, 61):
    data.append(i)
data = np.array(data)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [38]:
numbers = np.arange(1, 61)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [42]:
numbers.shape

(60,)

## Reshape and Ravel

In [ ]:
'''
Reshape -> Convert any dimension of array into another dimension array.
Ravel -> Converty any dimension of array into one dimension array./ flatten
'''

In [43]:
reshape_numbers = numbers.reshape(10, 6)
reshape_numbers

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [44]:
ravel_numbers = np.ravel(reshape_numbers)
ravel_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

## Slicing

In [48]:
ravel_numbers[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [57]:
for row in reshape_numbers[1:3]:
    print(row[1:3])

[8 9]
[14 15]


In [58]:
# array[row, col]
print(reshape_numbers[1:3, 1:3])

[[ 8  9]
 [14 15]]


#### Extract specific column

In [59]:
reshape_numbers[:,1]

array([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56])

In [60]:
reshape_numbers[:,2]

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57])

In [61]:
reshape_numbers[:,0]

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55])

In [62]:
products = np.array(['Mobile', 'TV', 'Bottle', 'Laptop', 'Desktop'])
products

array(['Mobile', 'TV', 'Bottle', 'Laptop', 'Desktop'], dtype='<U7')

In [64]:
name = np.array(['Ram', 'Bob', 'Charles'])
name

array(['Ram', 'Bob', 'Charles'], dtype='<U7')

## Boolean Indexing

In [68]:
filter_numbers = numbers < 20
numbers[filter_numbers]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [69]:
numbers[numbers < 20]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

## Array Broadcasting

In [ ]:
'''
Rules of Broadcasting
----------------------
1. All shape of array must be equal.
2. Either one shape row / column must be 1 and other must be equal.
'''

In [80]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]) # 3 x 3

arr2 = np.array([
    [4]
]) # 1 x 1

In [81]:
arr1 + arr2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])